# Generated by Django 4.2.3 on 2023-07-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='c1',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='c2',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='c3',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='c4',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
