# Generated by Django 4.2.3 on 2023-07-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_question_ans_question_c1_question_c2_question_c3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='c1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='c2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='c3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='c4',
            field=models.CharField(max_length=250),
        ),
    ]
